version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0

  frontend:
    build: ./frontend
    ports:
      - "3000:8080"
    environment:
      - REACT_APP_API_URL=http://localhost:7000
    depends_on:
      - backend